server:
    port: ${port:8801}
spring:
    application:
        name: techefx-product-stock-service
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        password: password@1234
        url: jdbc:mysql://127.0.0.1:3306/test?useSSL=false
        username: root
    devtools:
        restart:
            enabled: 'true'
    jpa:
        database: MYSQL
        hibernate:
            ddl-auto: create-drop
        show-sql: true
        properties:
            hibernate:
                hbm2ddl:
                    import_files: data.sql
    
